spring:
  application:
    name: rookies
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/web
    username: root
    password: 9999

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
server:
  error:
    include-stacktrace: always
    include-message: always

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  upload-dir: C:/rookies/upload/

thymeleaf:
  cache: false
  prefix: classpath:/templates/